import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({data}) {
  console.log("last")
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          SpaceX Launch Programs
        </h1>


        <div className={styles.grid}>
          <div className={styles.card}>
            <h1 className={styles.filters}>Filters</h1>
            <h2>Launch Year</h2>
            <div className={styles.buttons}>

              <button>2006</button>
              <button>2007</button>
              <button>2008</button>
              <button>2009</button>
              <button>2010</button>
              <button>2006</button>
              <button>2007</button>
              <button>2008</button>
              <button>2009</button>
              <button>2010</button>
              <button>2006</button>
            </div>
            <h2>Successful Launch</h2>
            <div className={styles.buttons}>
              <button>True</button>
              <button>False</button>
            </div>
            <h2>Successful Launch</h2>
            <div className={styles.buttons}>
              <button>True</button>
              <button>False</button>
            </div>
 

          </div>
          {data.map((e)=>{
            return(
            
            <div className={styles.card} key={e.flight_number}>
             
            <div className={styles.image}>
              <Image   src={e.links.mission_patch_small} width={200} height={200} layout="responsive" alt="Image" />
            </div>
            <h3>{e.mission_name} </h3>
            <h3>Mission Ids: {e.mission_id} </h3>

            
            <h3>Launch Year: {e.launch_year} </h3>
            
            <h3>Successful Launch: {e.launch_success.toString()} </h3>
            
            <h3>Successful Landing: {e.rocket.first_stage.cores[0].landing_intent.toString()}</h3>
            
            </div>
            );
         
        })}
 

        </div>
      </main>

      <footer className={styles.footer}>
        <a>
          Developed by Dulkifal
        </a>
      </footer>
    </div>
  )
 
}



// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://api.spacexdata.com/v3/launches?limit=100`)
    // const res = await fetch(`file:///F:/spacex/spacex/pages/he.js`)
  const data = await res.json()
   

  // Pass data to the page via props
  return { props: { data } }
}


